DEFAULT_TTL_SECONDS = 30.0
DEFAULT_STALE_TTL_SECONDS = 300.0
# Not an option: a few seconds is short enough that nobody needs to tune it.
MISSING_TTL_SECONDS = 5.0
MAX_CACHE_ENTRIES = 10_000
BULK_CACHE_KEY = "__all__"

DEFAULT_TIMEOUT_SECONDS = 2.0
RATE_LIMIT_STATUS = 429
NOT_MODIFIED_STATUS = 304
DEFAULT_BACKOFF_SECONDS = 5.0
MAX_BACKOFF_SECONDS = 60.0
